set encoding=utf-8 modelines=0 t_Co=16 
filetype plugin indent on

set viminfo^=! 
syntax on
colorscheme eldar
set cursorline number 
set showcmd ruler laststatus=2 display+=lastline 

set wildmode=longest,list,full wildmenu

set autoread autowriteall
set clipboard^=unnamed,unnamedplus

set shiftround smarttab expandtab
set linebreak autoindent breakindent
set cpo+=J

set ignorecase smartcase
set incsearch showmatch hlsearch

let mapleader=","
let maplocalleader=","
set backspace=indent,eol,start
nnoremap Q <nop>
nmap <Leader>. :cd %:p:h<CR>:pwd<CR>
nmap <Leader>.. :cd ..<CR>:pwd<CR>
nmap <Leader>w :w<CR>
nnoremap <ESC><ESC> :nohlsearch<CR><C-l>
inoremap jk <ESC>`^<C-l>
