set encoding=utf-8 modeline modelines=1 t_Co=16 
filetype plugin indent on

set viminfo^=! 
syntax on
colorscheme acmesque
set number showcmd ruler laststatus=2 display+=lastline 

set wildmode=longest,list,full wildmenu

set autoread autowriteall
set clipboard^=unnamed,unnamedplus

set shiftround smarttab expandtab
set linebreak autoindent breakindent noexpandtab
set cpo+=J

set ignorecase smartcase
set incsearch hlsearch shortmess-=S
let g:loaded_matchparen=1

set backspace=indent,eol,start
let mapleader=","
let maplocalleader=","
nnoremap Q <nop>
nnoremap <Leader>. :cd %:p:h<CR>:pwd<CR>
nnoremap <Leader>.. :cd ..<CR>:pwd<CR>
nnoremap <Leader>w :w<CR>
nnoremap <Space> za
nnoremap <Leader><Leader> <C-^>
nnoremap <C-l> :nohlsearch<CR><C-l>
inoremap jk <ESC>`^<C-l>
